"""Single source of truth for the bot's command surface.

The COMMAND_REGISTRY here drives THREE consumers:

1. `bot.py` — `/commands` renders the grouped text, post_init publishes the
   flat list to Telegram autocomplete via setMyCommands.
2. `morning.py` — re-writes `<LIFE_OS_ROOT>/dev/bot-commands.md` on every
   morning run so Cowork sees a fresh, comprehensive command reference
   without needing to talk to the bot.
3. `bot.py` startup — also re-writes the same file, so adding a command
   here and restarting is enough to keep the data tree in sync.

Adding a new bot command? Add it here. The doc-writer keeps the data tree
in lockstep automatically.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

# (group, command, one-line description). Group order determines doc order.
COMMAND_REGISTRY: list[tuple[str, str, str]] = [
    ("Daily flow", "plan",      "Show today's plan; check-in if a block is in progress"),
    ("Daily flow", "log",       "[domain] <what you did> — record a completed entry"),
    ("Daily flow", "ai",        "<text> — freeform note; Haiku tags and saves it"),

    ("Reshuffle",  "behind",    "Running behind — pick a scheduled task to drop"),
    ("Reshuffle",  "add",       "<event> @<time> [date] — anchored event w/ reminder; /add queue pins a carried task"),
    ("Reshuffle",  "skip",      "Skip a block for today (toggle)"),
    ("Reshuffle",  "move",      "<block> <HH:MM-HH:MM> — retime a block for today"),
    ("Reshuffle",  "extend",    "[N=30] — extend the in-progress block by N minutes"),
    ("Reshuffle",  "shift",     "[N=30] — push the rest of the day forward by N minutes"),
    ("Reshuffle",  "clearday",  "Clear today's block edits"),

    ("Inputs",     "note",      "[domain] <text> — save an ingest note"),
    ("Inputs",     "edit",      "inbox <text> | threshold <d>.<f> <v>"),
    ("Inputs",     "domain",    "list — show known domains"),

    ("Misc",       "evening",   "<brief> — Haiku summarizes your evening into the log"),
    ("Misc",       "mode",      "Show or switch plan mode (blocks | goals); /mode haiku on|off"),
    ("Misc",       "commands",  "Show this list"),
    ("Misc",       "start",     "Connectivity check"),
]


DOC_HEADER = """\
<!-- SCRIPT-OWNED: regenerated by bot.py (on startup) and morning.py.
     Do not edit by hand; edit COMMAND_REGISTRY in commands_doc.py instead.
     This file exists so Cowork sessions can see the current bot command
     surface without needing to talk to the bot. -->

# Telegram Bot — Command Reference

**Generated:** {generated}

The bot serves these commands; the legacy `bot.py --notify` / `--checkin` CLI
handles also exist for cron, but those aren't user-facing. Inline-keyboard
buttons (check-ins, conflict menus, skip lists, +15/+30/+60 extensions) are
described in the README; this file is the flat command index.

"""


def render_bot_commands_md(registry: list[tuple[str, str, str]] | None = None,
                           generated: str | None = None) -> str:
    """Render COMMAND_REGISTRY as the bot-commands.md body."""
    registry = registry if registry is not None else COMMAND_REGISTRY
    generated = generated or datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = [DOC_HEADER.format(generated=generated)]
    current_group = None
    for group, cmd, desc in registry:
        if group != current_group:
            lines.append(f"\n## {group}\n")
            lines.append("| Command | Description |")
            lines.append("|---------|-------------|")
            current_group = group
        lines.append(f"| `/{cmd}` | {desc} |")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_bot_commands_md(life_os_root) -> Path:
    """Write/refresh dev/bot-commands.md in the data tree. Returns the path."""
    out = Path(life_os_root) / "dev" / "bot-commands.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_bot_commands_md(), encoding="utf-8")
    return out
