"""compile() — normalize the four canonical task sources + logs into queue.yaml.

Deterministic and idempotent. Reads:
  - domains/<d>/tasks.md        (Type 3 goal-linked)
  - thresholds.yaml             (Type 4 perpetual recurring)
  - inbox.md                    (Type 1 floating; Type 2 when a `due:` is present)
  - daily/logs/                 (completion history -> urgency + eligibility)

Writes schedule/queue.yaml. NEVER calls an LLM (governing principle).

NOTE: schedule/ week files (Type 2 anchored events authored in schedule/weeks/)
are not yet defined in the tree; their parser is stubbed and additive. Dated
inbox items already provide Type 2 coverage for now.
"""
from __future__ import annotations

import re
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import yaml

from .constants import IMPORTANCE_WEIGHT, MANDATORY_WEEKLY_BOOST
from .days import expand_days
from .logs import (
    completions_this_week,
    done_task_ids,
    last_completion_for_domain,
    read_log_entries,
)
from .models import LintIssue, Placement, Task
from .tasks_parser import parse_tasks_file
from .urgency import cadence_debt_urgency, deadline_urgency

# Default slot mapping for Type 4 (thresholds.yaml) domains. Mirrors the domain
# columns in schedule/template.md. Domains absent here (or cadence as-scheduled)
# are event-driven and not auto-scheduled by compile().
THRESHOLD_DOMAIN_SLOTS = {
    "music-practice": ["practice-creative"],
    "production": ["practice-creative"],
    "novel": ["deep-work"],
    "reading": ["wind-down"],
    "fitness": ["exercise"],
    "career": ["deep-work", "admin"],
    "meals": ["admin"],
    "upkeep": ["admin"],   # chores cluster under Admin/Career (template.md)
}

DEFAULT_TASK4_DURATION = 60   # minutes, when unit is not "minutes"

QUEUE_HEADER = """\
# DERIVED STORE — DO NOT HAND-EDIT, DO NOT AUTHOR BY HAND.
#
# Regenerated by scheduler.compile_queue.compile() from the four canonical task
# sources plus the logs (thresholds.yaml, schedule/+inbox dates, domains/<d>/
# tasks.md, inbox.md, daily/logs/). To change what is scheduled, edit the
# SOURCES — never this file. See SYSTEM.md -> Scheduling Layer and
# DOMAIN-FORMAT.md section 7. `urgency` and `eligible` are computed here.
"""

_INBOX_LINE_RE = re.compile(r"^- \[[ xX]\]\s*(.+)$")
_DUE_RE = re.compile(r"due:\s*(fixed|hard|soft)\s+(\d{4}-\d{2}-\d{2})", re.IGNORECASE)


# --- Source normalizers ----------------------------------------------------

def _normalize_thresholds(thresholds: dict, lint: list,
                          domain_days: dict[str, list[str]] | None = None) -> list:
    """Normalize thresholds.yaml domains into Type 4 task records.

    `as-scheduled` cadence is normally skipped (event-driven). When a
    domain carries `days: [...]`, however, it emits a low-urgency Type 4
    "nudge" placeable on those weekdays — the chores model. The nudge
    never accrues cadence-debt and has importance `low`, so it falls
    through to whatever capacity remains on its eligible days.
    """
    domain_days = domain_days or {}
    tasks: list = []
    for domain, cfg in (thresholds or {}).items():
        if not isinstance(cfg, dict):
            continue
        cadence = cfg.get("cadence")
        days = domain_days.get(domain, [])
        if cadence is None:
            continue
        slots = THRESHOLD_DOMAIN_SLOTS.get(domain)
        if not slots:
            lint.append(LintIssue("warning", "thresholds.yaml",
                                  f"domain '{domain}' has cadence '{cadence}' but no slot mapping; skipped"))
            continue
        if cadence == "as-scheduled":
            if not days:
                continue  # truly event-driven; no auto-schedule
            # B6: as-scheduled + days = light recurring nudge on eligible days.
            tasks.append(Task(
                id=f"{domain}-recurring",
                title=f"{domain} (chores — {'/'.join(days)})",
                type=4,
                source="thresholds",
                domain=domain,
                importance="low",
                duration=DEFAULT_TASK4_DURATION,
                cadence="as-scheduled",
                placement=Placement(
                    cls="floating", slots=list(slots),
                    min_block=min(DEFAULT_TASK4_DURATION, 30),
                    days=list(days),
                ),
            ))
            continue
        unit = cfg.get("unit")
        target = cfg.get("target")
        minv = cfg.get("min")
        duration = int(target) if (unit == "minutes" and target) else DEFAULT_TASK4_DURATION
        min_block = int(minv) if (unit == "minutes" and minv) else min(duration, 30)
        tasks.append(Task(
            id=f"{domain}-recurring",
            title=f"{domain} ({cadence} cadence)",
            type=4,
            source="thresholds",
            domain=domain,
            importance="normal",
            duration=duration,
            target=target,
            unit=unit,
            min=int(minv) if minv else None,
            cadence=cadence,
            mandatory_weekly=cfg.get("mandatory-weekly"),
            placement=Placement(
                cls="floating", slots=list(slots), min_block=min_block,
                days=list(days),
            ),
        ))
    return tasks


def _normalize_inbox(text: str, today: date, lint: list) -> list:
    tasks: list = []
    n = 0
    for line in text.splitlines():
        m = _INBOX_LINE_RE.match(line.strip())
        if not m:
            continue
        n += 1
        body = m.group(1)
        parts = [p.strip() for p in body.split("|")]
        title = parts[0]
        deadline = None
        deadline_type = None
        waiting = False
        for seg in parts[1:]:
            due = _DUE_RE.search(seg)
            if due:
                deadline_type = due.group(1).lower()
                try:
                    deadline = datetime.strptime(due.group(2), "%Y-%m-%d").date()
                except ValueError:
                    lint.append(LintIssue("warning", "inbox.md", f"bad due date in: {seg}"))
            elif seg.lower().startswith("waiting:"):
                waiting = seg.split(":", 1)[1].strip().lower() in ("true", "yes", "1")
        ttype = 2 if deadline else 1
        tasks.append(Task(
            id=f"inbox-{n:03d}",
            title=title,
            type=ttype,
            source="inbox",
            domain="",
            importance="normal",
            duration=30,
            waiting=waiting,
            placement=Placement(cls="floating", slots=["admin"], min_block=30),
            deadline=deadline,
            deadline_type=deadline_type,
        ))
    return tasks


# --- compile() -------------------------------------------------------------

def compile_queue(root: Path, today: Optional[date] = None) -> tuple[list, list]:
    """Build the normalized+computed task list and lint list. In-memory only."""
    today = today or date.today()
    tasks: list = []
    lint: list = []

    # Read thresholds first so domain-level `days` is available for Type 3
    # inheritance and the as-scheduled+days light-nudge path.
    thresholds_path = root / "thresholds.yaml"
    thresholds = {}
    domain_days: dict[str, list[str]] = {}
    if thresholds_path.exists():
        thresholds = yaml.safe_load(thresholds_path.read_text(encoding="utf-8")) or {}
        for domain, cfg in (thresholds or {}).items():
            if not isinstance(cfg, dict) or not cfg.get("days"):
                continue
            try:
                domain_days[domain] = expand_days(cfg["days"])
            except ValueError as e:
                lint.append(LintIssue("error", "thresholds.yaml",
                                      f"domain '{domain}' {e}"))

    # Type 3 — tasks.md per domain
    domains_dir = root / "domains"
    if domains_dir.is_dir():
        for tasks_md in sorted(domains_dir.glob("*/tasks.md")):
            domain = tasks_md.parent.name
            _next_id, dtasks, issues = parse_tasks_file(tasks_md, domain)
            lint.extend(issues)
            # Inherit domain-level days when the task didn't author its own.
            inherited = domain_days.get(domain)
            if inherited:
                for t in dtasks:
                    if not t.placement.days:
                        t.placement.days = list(inherited)
            tasks.extend(dtasks)

    # Type 4 — thresholds.yaml (with domain-level days passed through)
    if thresholds:
        tasks.extend(_normalize_thresholds(thresholds, lint, domain_days))

    # Type 1/2 — inbox.md
    inbox_path = root / "inbox.md"
    if inbox_path.exists():
        tasks.extend(_normalize_inbox(inbox_path.read_text(encoding="utf-8"), today, lint))

    # Completion history
    entries = read_log_entries(root)
    done = done_task_ids(entries)
    all_ids = {t.id for t in tasks}

    # Per-task computed fields
    for t in tasks:
        u = deadline_urgency(t.deadline, t.deadline_type, today)
        if t.type == 4:
            last = last_completion_for_domain(entries, t.domain)
            u += cadence_debt_urgency(
                t.cadence, last, today, days=t.placement.days)
            if t.mandatory_weekly and completions_this_week(entries, t.domain, today) == 0:
                t.mandatory_due = True
                u += MANDATORY_WEEKLY_BOOST
        t.urgency = u

        reasons = []
        if t.waiting:
            reasons.append("waiting")
        if t.not_before and t.not_before > today:
            reasons.append(f"not-before {t.not_before.isoformat()}")
        unmet = [d for d in t.depends_on if d not in done]
        if unmet:
            reasons.append("depends-on: " + ",".join(unmet))
        t.eligible = not reasons
        t.blocked_reason = "; ".join(reasons) or None

        # Lint: dangling depends-on, drift
        for d in t.depends_on:
            if d not in all_ids and d not in done:
                lint.append(LintIssue("warning", t.id,
                                      f"dangling depends-on '{d}' (unknown id, not logged done)"))
        if t.id in done:
            lint.append(LintIssue("warning", t.id,
                                  "logged done but still present in tasks.md (prune in evening synthesis)"))

    _propagate_critical_path(tasks)
    return tasks, lint


def _propagate_critical_path(tasks: list) -> None:
    """A blocker inherits the urgency of what it blocks (DOMAIN-FORMAT.md §7.5)."""
    by_id = {t.id: t for t in tasks}
    for _ in range(len(tasks) + 1):
        changed = False
        for t in tasks:
            for dep_id in t.depends_on:
                dep = by_id.get(dep_id)
                if dep is not None and dep.urgency < t.urgency:
                    dep.urgency = t.urgency
                    changed = True
        if not changed:
            break


# --- queue.yaml serialization boundary -------------------------------------

def write_queue(root: Path, tasks: list, lint: list, generated: Optional[str] = None) -> None:
    generated = generated or datetime.now().isoformat(timespec="seconds")
    payload = {
        "generated": generated,
        "tasks": [t.to_queue_dict() for t in tasks],
        "lint": [i.to_dict() for i in lint],
    }
    body = yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False)
    (root / "schedule" / "queue.yaml").write_text(QUEUE_HEADER + "\n" + body, encoding="utf-8")


def load_queue(root: Path) -> tuple[list, list, Optional[str]]:
    """Read queue.yaml back into Task objects (frozen urgency for reshuffle)."""
    path = root / "schedule" / "queue.yaml"
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    tasks = [Task.from_queue_dict(d) for d in (data.get("tasks") or [])]
    lint = [LintIssue(**i) for i in (data.get("lint") or [])]
    return tasks, lint, data.get("generated")


def compile_to_file(root: Path, today: Optional[date] = None) -> tuple[list, list]:
    """compile() then persist to schedule/queue.yaml. Returns (tasks, lint)."""
    tasks, lint = compile_queue(root, today)
    write_queue(root, tasks, lint)
    return tasks, lint
